version: '3.7'
services:

    unturned-store:
        image: unturned-store:${BRANCH_NAME}
        container_name: unturnedstore-${BRANCH_NAME}
        build:
            context: ./
        restart: unless-stopped
        ports:
            - 127.0.0.1:${EXT_PORT}:5000
        networks:
            unturnedstore:
                ipv4_address: ${INT_IP}
        environment:
            - ConnectionStrings__Default=${CONNECTION_STRING}
            - IsMockEnabled=${MOCK_ENABLED}
            - Payment__BaseAddress=${PAYMENT_ADDRESS}
            - Payment__APIKey=${PAYMENT_APIKEY}
            - Discord__SendPluginUpdateWebhookUrl=${UPDATE_WEBHOOK}
            - Discord__SendNewReviewWebhookUrl=${NEWREVIEW_WEBHOOK}
            - Discord__SendProductReleaseWebhookUrl=${RELEASE_WEBHOOK}
            - Discord__AdminNotificationsWebhookUrl=${ADMIN_WEBHOOK}
            - SteamWebAPIKey=${STEAM_APIKEY}
            - Logging__LogLevel__Default=${LOGLEVEL_DEFAULT}
            - Logging__LogLevel__Microsoft=${LOGLEVEL_MICROSOFT}
            - Logging__LogLevel__Microsoft.Hosting.Lifetime=${LOGLEVEL_HOSTING}
            - AllowedHosts=${ALLOWED_HOSTS}
        
networks:
    unturnedstore:
        name: unturned-store
        external: true